### PR TITLE
Fixes to be compliant with JSONLogic Spec

### PR DESCRIPTION
**Pull request by bhgames**
@kennethgeerts With these changes your library is fully compliant with the JSONLogic spec, and passes all tests. My own production app will point to my fork until you have time to review! Thanks.

### CODE REVIEW

**Comment by bhgames** [comment]
@kennethgeerts anybody alive here?

**Comment by bhgames** [comment]
Hey, by the way, I'm happy to take over and become the primary fork of this project if you're unable to continue with it. We're using it in a production application so we've got an incentive to keep it up.

**Comment by kennethgeerts** [comment]
Hi @bhgames !
Thanks for your interest and sorry I'm late to react on this one.
As I haven't got the time or interest anymore to maintain this, I'm happy to transfer the repo to you if you're still interested.

All the best!

**Comment by bhgames** [comment]
@kennethgeerts sure. How does one do a repo transfer? I've never done that before.

**Comment by kennethgeerts** [comment]
I can do it in the repo settings. Although I get:

> bhgames/json-logic-ruby already exists

Can you rename or delete your fork, so I can try again?

Cheers,
Kenneth

**Comment by bhgames** [comment]
It's been renamed @kennethgeerts . What about the rubygem access? How can I push a new version?

**Comment by bhgames** [comment]
@kennethgeerts  ?

**Comment by bhgames** [comment]
@kennethgeerts bump

**Comment by kennethgeerts** [comment]
Hi Jordan,

It seems you'll have to delete your fork as well, for this to work.

I get the following error when trying to transfer:
> bhgames already has a repository in the kennethgeerts/json-logic-ruby network

**Comment by bhgames** [comment]
okay @kennethgeerts it's been deleted. How do I also get permission to push a new version of the gem?

**Comment by kennethgeerts** [comment]
The transfer is requested. I've also added you as a gem owner, so you can push.

```sh
❯ gem owner json_logic --add jordanmprince@gmail.com
Owner added successfully.
Owners for gem: json_logic
- jordanmprince@gmail.com
- kenneth.geerts@up-nxt.com
```

**Pull request closed without merging**
